from django.contrib import admin  
from django.urls import path 
from django.urls import path,include 
from loginsignup import views
from loginsignup.views import UserList
from loginsignup.views import EmployeeAPIView,ChatgptAPIView,AssistantchatAPIView,Interview_questionAPIView,StudynotesAPIView,Restaurant_reviewAPIView,Turn_byAPIView
from loginsignup.views import EmployeeAPIView,ChatgptAPIView,MarvchatbotAPIView,ChatappsAPIView,Recipe_creatorAPIView,Eassy_outlineAPIView,ThirdpersonAPIView,MicrohorrorAPIView,JavascriptAPIView
from loginsignup.views import EmployeeAPIView,ChatgptAPIView,AnalogymakerAPIView,WritepythondocAPIView,MoodcolorAPIView,FriendchatAPIView,Javascript_pythonAPIView,Extract_contactAPIView,SqlrequestAPIView
from loginsignup.views import EmployeeAPIView,ChatgptAPIView,Airport_codeAPIView,Tweet_classifierAPIView,Science_fictionAPIView,LanguagemodalAPIView,Javascript_chatbotAPIView,SpreadsheetAPIView,PythonbugAPIView
from loginsignup.views import EmployeeAPIView,ChatgptAPIView,SummarizationAPIView,Pro_descAPIView,FactualansAPIView,KeywordsAPIView,ExplaincodeAPIView,AdvancetweetAPIView,Translate_proAPIView
from loginsignup.views import EmployeeAPIView,ChatgptAPIView,TimecomplexityAPIView,MovieemojiAPIView,Python_naturalAPIView,ClassificationAPIView,Parse_unstructureAPIView,NotessummaryAPIView,Fitness_ideaAPIView
from loginsignup.views import EmployeeAPIView,SqltranslateAPIView,ProductgeneratorAPIView,ChatgptAPIView,Natural_languageAPIView,English_translateAPIView,TextcommandAPIView,NaturalapiAPIView,SummarizeAPIView,GrammerAPIView,Question_analysisAPIView
from loginsignup.views import ListUsers,CustomAuthToken
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [  
    path('admin/', admin.site.urls),
    path('employee/',views.employee_list,name='employee'),
    path('chatdashboard/',views.chatdashboard_list,name='chatdashboard'),
    path('employee/<int:id>/', views.employee_form,name='employee_update'), # get and post req. for update operation
    path('employee/delete/<int:id>/',views.employee_delete,name='employee_delete'), 
    path('employee/add/',views.employee_form,name='employee_insert'),

    path('aidashboard/',views.aidashboard_list,name='aidashboard'),    
    path('aidashboard/add/',views.aidashboard_form,name='aidashboard_insert'),
    path('aidashboard/<int:id>/', views.aidashboard_form,name='aidashboard_update'), # get and post req. for update operation
    path('aidashboard/delete/<int:id>/',views.aidashboard_delete,name='aidashboard_delete'),

    path('recipe/add/',views.recipe_form,name='recipe_insert'),
   path('vowel/',views.vowel_form,name='vowel_list'),
    path('paneer/',views.paneer_form,name='paneer_list'),
    path('vegcurry/',views.vegcurry_form,name='vegcurry_list'),
    path('chicken/',views.chicken_form,name='chicken_list'),
    path('recipe_detail/<int:id>/', views.recipe_detail,name='recipe_detail'),

    path('student',include('student.urls')), 
    path('admin/', admin.site.urls),
    path('',views.SignupPage,name='signup'),
    path('login/',views.LoginPage,name='login'),
    path('chatgpt/',views.chat_with_gpt,name='chatgpt'),
    path('chatapi/',views.chat_with_api,name='chatapi'),  
    path('chat/',views.chat,name='chat'), 
    path('dashboard/',views.dashboard,name='dashboard'),
    path('chatimage/',views.get_image_api,name='chatimage'),
    path('home/',views.HomePage,name='home'),
    path('logout/',views.LogoutPage,name='logout'),
    path('api/users/', ListUsers.as_view()),   
    path('api/token/', CustomAuthToken.as_view()),
    path('myemployee/', EmployeeAPIView.as_view()),
    path('mychatgpt/', ChatgptAPIView.as_view()),

    path('question_analysis',views.question_analysis,name='question_analysis'),
    path('myquestion_analysis/', Question_analysisAPIView.as_view()),
    path('api/myquestion_analysis/', views.api_question_analysis, name='api_question_analysis'),
    path('grammer_correction',views.grammer_correction,name='grammer_correction'),
    path('mygrammer_correction/', GrammerAPIView.as_view()),
    path('api/grammer_correction/',views.api_grammer_correction,name='api_grammer_correction'),
    path('sql_translates',views.sql_translates,name='sql_translates'),
    path('mysql_transalate/', SqltranslateAPIView.as_view()),
    path('api/sql_translates/',views.api_sql_translates,name='api_sql_translates'),
    path('product_generator',views.product_generator,name='product_generator'),
    path('myproduct_generator/', ProductgeneratorAPIView.as_view()),
    path('api/product_generator/',views.api_product_generator,name='api_product_generator'),
    path('summarize_gender',views.summarize_gender,name='summarize_gender'),
    path('mysummarize_gender/', SummarizeAPIView.as_view()),
    path('api/summarize_gender/',views.api_summarize_gender,name='api_summarize_gender'),
    path('natural_api',views.natural_api,name='natural_api'),
    path('mynatural_api/', NaturalapiAPIView.as_view()),
    path('api/natural_api/',views.api_natural_api,name='ap_natural_api'),
    path('text_command',views.text_command,name='text_command'),
    path('mytext_command/', TextcommandAPIView.as_view()),
    path('api/text_command/',views.api_text_command,name='api_text_command'),
    path('english_translate',views.english_translate,name='english_translate'),
    path('myenglish_translate/', English_translateAPIView.as_view()),
    path('api/english_translate/',views.api_english_translate,name='api_english_translate'),
    path('natural_language_stripe',views.natural_language_stripe,name='natural_language_stripe'),
    path('mynatural_language_stripe/', Natural_languageAPIView.as_view()),
    path('api/natural_language_stripe/',views.api_natural_language_stripe,name='api_natural_language_stripe'),  

   

    path('Vr_fitness_idea_generator',views.Vr_fitness_idea_generator,name='Vr_fitness_idea_generator'),
    path('myfitness_idea_generator/', Fitness_ideaAPIView.as_view()),
    path('api/Vr_fitness_idea_generator/',views.api_Vr_fitness_idea_generator,name='api_Vr_fitness_idea_generator'),
    path('notes_to_summary',views.notes_to_summary,name='notes_to_summary'),
    path('mynotes_to_summary/', NotessummaryAPIView.as_view()),
    path('api/notes_to_summary/',views.api_notes_to_summary,name='api_notes_to_summary'),
    path('parse_unstructured_data',views.parse_unstructured_data,name='parse_unstructured_data'),
    path('myparse_unstructured_data/', Parse_unstructureAPIView.as_view()),
    path('api/parse_unstructured_data/',views.api_parse_unstructured_data,name='api_parse_unstructured_data'),
    path('classification',views.classification,name='classification'),
    path('myclassification/', ClassificationAPIView.as_view()),
    path('api/classification/',views.api_classification,name='api_classification'),
    path('python_to_natural_language',views.python_to_natural_language,name='python_to_natural_language'),
    path('mypython_to_natural_language/', Python_naturalAPIView.as_view()),
    path('api/python_to_natural_language/',views.api_python_to_natural_language,name='api_python_to_natural_language'),
    path('movie_to_emoji',views.movie_to_emoji,name='movie_to_emoji'),
    path('mymovie_to_emoji/', MovieemojiAPIView.as_view()),
    path('api/movie_to_emoji/',views.api_movie_to_emoji,name='api_movie_to_emoji'),
    path('calculate_time_complexity',views.calculate_time_complexity,name='calculate_time_complexity'), 
    path('mycalculate_time_complexity/', TimecomplexityAPIView.as_view()),
    path('api/calculate_time_complexity/',views.api_calculate_time_complexity,name='api_calculate_time_complexity'),

    path('translate_programming_language',views.translate_programming_language,name='translate_programming_language'),
    path('mytranslate_programming_language/', Translate_proAPIView.as_view()),
    path('api/translate_programming_language/',views.api_translate_programming_language,name='api_translate_programming_language'),
    path('advanced_tweet_classifier',views.advanced_tweet_classifier,name='advanced_tweet_classifier'),
    path('myadvanced_tweet_classifier/', AdvancetweetAPIView.as_view()),
    path('api/advanced_tweet_classifier/',views.api_advanced_tweet_classifier,name='api_advanced_tweet_classifier'),
    path('explain_code',views.explain_code,name='explain_code'),
    path('myexplain_code/', ExplaincodeAPIView.as_view()),
    path('api/explain_code/',views.api_explain_code,name='api_explain_code'),
    path('keywords',views.keywords,name='keywords'),
    path('mykeywords/', KeywordsAPIView.as_view()),
    path('api/keywords/',views.api_keywords,name='api_keywords'),
    path('factual_answering',views.factual_answering,name='factual_answering'),
    path('myfactual_answering/', FactualansAPIView.as_view()),
    path('api/factual_answering/',views.api_factual_answering,name='api_factual_answering'),
    path('ad_form_product_description',views.ad_form_product_description,name='ad_form_product_description'),
    path('myad_form_product_description/', Pro_descAPIView.as_view()),
    path('api/ad_form_product_description/',views.api_ad_form_product_description,name='api_ad_form_product_description'),
    path('summarization',views.summarization,name='summarization'), 
    path('mysummarization/', SummarizationAPIView.as_view()),
    path('api/summarization/',views.api_summarization,name='api_summarization'), 

    path('python_bug_fixer',views.python_bug_fixer,name='python_bug_fixer'),
    path('mypython_bug_fixer/', PythonbugAPIView.as_view()),
    path('api/python_bug_fixer/',views.api_python_bug_fixer,name='api_python_bug_fixer'),
    path('spreadsheet_creator',views.spreadsheet_creator,name='spreadsheet_creator'),
    path('myspreadsheet_creator/', SpreadsheetAPIView.as_view()),
    path('api/spreadsheet_creator/',views.api_spreadsheet_creator,name='api_spreadsheet_creator'),
    path('java_script_helper_chat_bot',views.java_script_helper_chat_bot,name='java_script_helper_chat_bot'),
    path('myjava_script_helper_chat_bot/', Javascript_chatbotAPIView.as_view()),
    path('api/java_script_helper_chat_bot/',views.api_java_script_helper_chat_bot,name='api_java_script_helper_chat_bot'),
    path('mi_language_model_tutor',views.mi_language_model_tutor,name='mi_language_model_tutor'),
    path('mymi_language_model_tutor/', LanguagemodalAPIView.as_view()),
    path('api/mi_language_model_tutor/',views.api_mi_language_model_tutor,name='api_mi_language_model_tutor'),
    path('science_fiction_book_list_maker',views.science_fiction_book_list_maker,name='science_fiction_book_list_maker'),
    path('myscience_fiction_book_list_maker/', Science_fictionAPIView.as_view()),
    path('api/science_fiction_book_list_maker/',views.api_science_fiction_book_list_maker,name='api_science_fiction_book_list_maker'),
    path('tweet_classifier',views.tweet_classifier,name='tweet_classifier'),
    path('mytweet_classifier/', Tweet_classifierAPIView.as_view()),
    path('api/tweet_classifier/',views.api_tweet_classifier,name='api_tweet_classifier'),
    path('airport_code_extractor',views.airport_code_extractor,name='airport_code_extractor'),  
    path('myairport_code_extractor/', Airport_codeAPIView.as_view()),
    path('api/airport_code_extractor/',views.api_airport_code_extractor,name='api_airport_code_extractor'),

    path('sql_request',views.sql_request,name='sql_request'),
    path('mysql_request/', SqlrequestAPIView.as_view()),
    path('api/sql_request/',views.api_sql_request,name='api_sql_request'),
    path('extract_contact_information',views.extract_contact_information,name='extract_contact_information'),
    path('myextract_contact_information/', Extract_contactAPIView.as_view()),
    path('api/extract_contact_information/',views.api_extract_contact_information,name='api_extract_contact_information'),
    path('java_script_to_python',views.java_script_to_python,name='java_script_to_python'),
    path('myjava_script_to_python/', Javascript_pythonAPIView.as_view()),
    path('api/java_script_to_python/',views.api_java_script_to_python,name='api_java_script_to_python'),
    path('friend_chart',views.friend_chart,name='friend_chart'),
    path('myfriend_chart/', FriendchatAPIView.as_view()),
    path('api/friend_chart/',views.api_friend_chart,name='api_friend_chart'),
    path('mood_to_color',views.mood_to_color,name='mood_to_color'),
    path('mymood_to_color/', MoodcolorAPIView.as_view()),
    path('api/mood_to_color/',views.api_mood_to_color,name='api_mood_to_color'),
    path('write_a_ python_doc_string',views.write_a_python_doc_string,name='write_a_ python_doc_string'),
    path('mywrite_a_ python_doc_string/', WritepythondocAPIView.as_view()),
    path('api/write_a_ python_doc_string/',views.api_write_a_python_doc_string,name='api_write_a_python_doc_string'),
    path('analogy_maker',views.analogy_maker,name='analogy_maker'), 
    path('myanalogy_maker/', AnalogymakerAPIView.as_view()),
    path('api/analogy_maker/',views.api_analogy_maker,name='api_analogy_maker'), 

    path('java_script_online_function',views.java_script_online_function,name='java_script_online_function'),
    path('myjava_script_online_function/', JavascriptAPIView.as_view()),
    path('api/java_script_online_function/',views.api_java_script_online_function,name='api_java_script_online_function'),
    path('micro_horror_story_creator',views.micro_horror_story_creator,name='micro_horror_story_creator'),
    path('mymicro_horror_story_creator/', MicrohorrorAPIView.as_view()),
    path('api/micro_horror_story_creator/',views.api_micro_horror_story_creator,name='api_micro_horror_story_creator'),
    path('third_person_convertor',views.third_person_convertor,name='third_person_convertor'),
    path('mythird_person_convertor/', ThirdpersonAPIView.as_view()),
    path('api/third_person_convertor/',views.api_third_person_convertor,name='api_third_person_convertor'),
    path('eassy_outline',views.eassy_outline,name='eassy_outline'),
    path('myeassy_outline/', Eassy_outlineAPIView.as_view()),
    path('api/eassy_outline/',views.api_eassy_outline,name='api_eassy_outline'),
    path('recipe_creator',views.recipe_creator,name='recipe_creator'),
    path('myrecipe_creator/', Recipe_creatorAPIView.as_view()),
    path('api/recipe_creator/',views.api_recipe_creator,name='api_recipe_creator'),
    path('chat',views.chat,name='chat'),
    path('mychat/', ChatappsAPIView.as_view()),
    path('api/chat/',views.api_chat,name='api_chat'),
    path('marv_the_sarcastic_chat_bot',views.marv_the_sarcastic_chat_bot,name='marv_the_sarcastic_chat_bot'), 
    path('mymarv_the_sarcastic_chat_bot/', MarvchatbotAPIView.as_view()),
    path('api/marv_the_sarcastic_chat_bot/',views.api_marv_the_sarcastic_chat_bot,name='api_marv_the_sarcastic_chat_bot'),

    path('turn_by_turn_direction',views.turn_by_turn_direction,name='turn_by_turn_direction'),
    path('myturn_by_turn_direction/', Turn_byAPIView.as_view()),
    path('api/turn_by_turn_direction/',views.api_turn_by_turn_direction,name='api_turn_by_turn_direction'),
    path('reastaurant_review_creator',views.reastaurant_review_creator,name='reastaurant_review_creator'),
    path('myreastaurant_review_creator/', Restaurant_reviewAPIView.as_view()),
    path('api/reastaurant_review_creator/',views.api_reastaurant_review_creator,name='api_reastaurant_review_creator'),
    path('create_study_notes',views.create_study_notes,name='create_study_notes'),
    path('mycreate_study_notes/', StudynotesAPIView.as_view()),
    path('api/create_study_notes/',views.api_create_study_notes,name='api_create_study_notes'),
    path('interview_Question',views.interview_Question,name='interview_Question'),
    path('myinterview_Question/', Interview_questionAPIView.as_view()),
    path('api/interview_Question/',views.api_interview_Question,name='api_interview_Question'),
    path('assistant_chat',views.assistant_chat,name='assistant_chat'),  
    path('myassistant_chat/', AssistantchatAPIView.as_view()), 




    path('nlpdashboard/',views.nlp_dashboard,name='nlpdashboard'),
    path('feadashboard/',views.feature_dashboard,name='feadashboard'),
    path('fillmaskdashboard/',views.fill_maskdashboard,name='fillmaskdashboard'),
    path('nerdashboard/',views.ner_dashboard,name='nerdashboard'),
    path('questiondashboard/',views.question_dashboard,name='questiondashboard'),
    path('sentimentdashboard/',views.sentiment_dashboard,name='sentimentdashboard'),
    path('summarizationdashboard/',views.summarization_dashboard,name='summarizationdashboard'),
    path('textgendashboard/',views.text_gen_dashboard,name='textgendashboard'),
    path('translationdashboard/',views.translation_dashboard,name='translationdashboard'),
    path('zeroshotdashboard/',views.zeroshot_dashboard,name='zeroshotdashboard'),

    path('fillmask/add/',views.fillmask_form,name='fill_mask'),
    path('ner/add/',views.ner_form,name='ner'),
    path('question/add/',views.question_form,name='question'),
    path('sentiment/add/',views.sentiment_form,name='sentiment'),
    path('summarize/add/',views.summarize_form,name='summarize'),
    path('textgeneration/add/',views.textgen_form,name='textgen'),
    path('translation/add/',views.translation_form,name='translation'),
    path('prediction/add/',views.prediction_form,name='prediction'),    
    path('sentiment/',views.sentiments_dashboard,name='sentiment'),
    path('sentiment/adds/',views.mysentiment_form,name='sentiment_insert'),
    path('sentiment_detail/', views.sentiment_detail,name='sentiment_detail'),
    path('allsentiment/add/',views.allsentiment_form,name='allsentiment_insert'),
    path('allsentiment_reason/',views.allsentiment_reason,name='allsentiment_reason'), 

    path('allsentiment_reasondetail/<int:id>/',views.allsentiment_reasondetail,name='allsentiment_reasondetail'),
    path('allsentiment_solution/',views.allsentiment_solution,name='allsentiment_solution'), 
    path('allsentiment_solutiondetail/<int:id>/',views.allsentiment_solutiondetail,name='allsentiment_solutiondetail'),
   
    path('sentiment_analysis_view/',views.sentiment_analysis_view,name='sentiment_analysis_view'),
    



]  

