# Generated by Django 4.1.9 on 2023-06-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0007_ad_form_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginsignup.chatcategory'),
            preserve_default=False,
        ),
    ]
