# Generated by Django 4.1.9 on 2023-06-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0008_chatmessage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
