# Generated by Django 4.1.9 on 2023-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0011_recipe_recipe_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
