# Generated by Django 4.1.9 on 2023-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0012_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
