# Generated by Django 4.1.9 on 2023-06-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0015_predict_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='pre_sentiment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
