# Generated by Django 4.1.9 on 2023-06-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0016_sentiment_pre_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=10)),
            ],
        ),
    ]
